export enum EnvKeys {
  PORT = "PORT",
  DATABASE_URL = "DATABASE_URL",
  SYNC_DB = "SYNC_DB",
  IS_LOCAL = "IS_LOCAL",
  REDIS_URL = "REDIS_URL",
  REDIS_PORT = "REDIS_PORT",
  BASE_URL = "BASE_URL",
  BASE_CLIENT_URL = "BASE_CLIENT_URL",
  IS_PROD = "IS_PROD",
  REDIS_PASSWORD = "REDIS_PASSWORD",
}
